version: "3.7"
services:
  postgres:
    image: postgres:14-alpine
    container_name: remix-blues-stack
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - remix-blues-stack:/var/lib/postgresql/data
volumes:
  remix-blues-stack:
